{% set name = "ipyvue" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 408b5e6a64e203fc679f447a071e3dbc178ab2906982f248adf722fc84773ffa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyvue

about:
  home: http://github.com/mariobuikhuizen/ipyvue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widgets base for Vue libraries

  description: |
    Jupyter widgets base for Vue libraries

extra:
  recipe-maintainers:
    - mariobuikhuizen
