{% set name = "ipyvue" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b1381bd120184f970a5d66deac33b8592a666c8e1ab7a5afd33ecff342e0a95

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipyvue

about:
  home: http://github.com/mariobuikhuizen/ipyvue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widgets base for Vue libraries

  description: |
    Jupyter widgets base for Vue libraries

extra:
  recipe-maintainers:
    - mariobuikhuizen
