{% set name = "ipyvue" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d6c4becdc11013be5485fd1fb19741501b0ef030e9bdd6fe4ddd5d1a9c62362

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyvue

about:
  home: http://github.com/mariobuikhuizen/ipyvue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widgets base for Vue libraries

  description: |
    Jupyter widgets base for Vue libraries

extra:
  recipe-maintainers:
    - mariobuikhuizen
